---
- name: " NTP configuration using RESTCONF" 
  hosts: R1
  connection: local
  tasks:
    - name: "Pull restconf data" 
      uri: 
#        url: "https://{{ ansible_host}}/restconf/data/native/ntp"
        url: "https://{{ ansible_host}}/restconf/data/native/interface"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET 
        return_content: true 
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false 
      register: result 

    - name: "Print Result"
      debug:
        msg: "{{ result.json }}"