---
- name: NAPALM get_facts and get_interfaces
  hosts: pe_routers
  gather_facts: False
  tasks:
    - name: napalm get_facts
      napalm_get_facts:
        filter: facts,interfaces

    - debug:
        var: napalm_facts