---
- name: "Testing NAPAM"
  hosts: pe_routers
  connection: network_cli


  tasks:
    - name: "Pull data using getters"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user}}"
        password: "{{ ansible_ssh_pass}}"
        dev_os: "{{ napalm_platform }}"
        filter: ["facts"]
      register: output 


    - name: Print output
      debug:
        msg: "{{ output }}"