---
- hosts: rr_routers
  connection: ansible.netcommon.netconf
  tasks:
    - name: Get configuration and state data from startup datastore
      ansible.netcommon.netconf_get:
        source: running
      register: output 

    - name: print output 
      debug:
        msg: "{{ output }}"

    - name: Get configuration and state data in JSON format
      ansible.netcommon.netconf_get:
        display: xml
        filter: <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"></interface-configurations>
      register: output1

    - name: print output 
      debug:
        msg: "{{ output1.stdout_lines[0] }}"

    - name: use lookup filter to provide xml configuration 
      ansible.netcommon.netconf_config:
        content: "{{ lookup('file', './ntp-config.xml') }}"