---
# Using merged

# Before state:
# -------------
#
# router-ios#sh running-config | section ^router ospf
# router-ios#
- name: OSPF CONFIG playbook
  hosts: R3
  connection: network_cli 
  tasks:
    - name: Merge provided OSPF V2 configuration
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: 3.3.3.3
              network:
                - address: 0.0.0.0
                  wildcard_bits: 255.255.255.255
                  area: 0
        state: merged
    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified

    - name: show run command
      cisco.ios.ios_command:
        commands: sh start | s router ospf 
      register: output 

    - name: Printout the  output 
      debug:
        msg: "{{ output.stdout_lines[0] }}"