---
ntp_server_ip: "10.101"
lb_name: "7631"

local_vrfs:
  - name: red
    description: "Red VRF"
    rd: "1:400"
    interfaces:
      - Loopback{{lb_name}}11

  - name: blue
    description: "Blue VRF"
    rd: "1:410"
    interfaces:
      - Loopback{{lb_name}}12

  - name: green
    description: "Green VRF"
    rd: "1:420"
    interfaces:
      - Loopback{{lb_name}}13

  - name: yellow
    description: "Yellow VRF"
    rd: "1:430"
    interfaces:
      - Loopback{{lb_name}}12