---
- name: Playbook to retrive interface facts 
  hosts: iosxe 
  gather_facts: no


  tasks:
  - name: retrive ios facts 
    vars:
      ansible_connection: ansible.netcommon.network_cli 
    cisco.ios.ios_facts: 
        gather_subset: interfaces 

  - name: print out interface information 
    debug:
      var: ansible_net_interfaces