---

- name: "Testing Ansible"
  hosts: R1, R2
  connection: network_cli

  tasks:
    - name: "Sending show command"
      cisco.ios.ios_command:
        commands:
          - show ip int bri
          - show run | sec router ospf
          - show run | sec router bgp
          - sh run | sec ntp server
      register: command_output

    - name: "Print the output"
      debug:
        msg: "{{ command_output }}"